export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAILURE: "LOGIN_FAILURE",

    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",

    REGISTER_REQUEST: "REGISTER_REQUEST",
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILURE: "REGISTER_FAILURE"
}
export const profileConstants = {
    GET_USER_PROFILE_REQUEST: "GET_USER_PROFILE_REQUEST",
    GET_USER_PROFILE_SUCCESS: "GET_USER_PROFILE_SUCCESS",
    GET_USER_PROFILE_FAILURE: "GET_USER_PROFILE_FAILURE",

    UPLOAD_PROFILE_PHOTO_REQUEST: "UPLOAD_PROFILE_PHOTO_REQUEST",
    UPLOAD_PROFILE_PHOTO_SUCCESS: "UPLOAD_PROFILE_PHOTO_SUCCESS",
    UPLOAD_PROFILE_PHOTO_FAILURE: "UPLOAD_PROFILE_PHOTO_FAILURE",
    UPLOAD_DATA_REQUEST: "UPLOAD_DATA_REQUEST",
    UPLOAD_DATA_SUCCESS: "UPLOAD_DATA_SUCCESS",
    UPLOAD_DATA_FAILURE: "UPLOAD_DATA_FAILURE",
}